namespace Nice.Label._017.Keygen
{
	public enum ActivationErrorCode
	{
		ActivationLimitReached,
		CompanyMustBeEntered,
		CountryMustBeEntered,
		EmailMustBeEntered,
		ErrorRetrieveingDataFromDatabase,
		ErrorUpdatingDatabaseData,
		ErrorWhileCreatingActivationCode,
		LicenseKeyIsNotFoundInDatabase,
		LicenseKeyIsNotValid,
		LicenseKeyIsNotValidAnymore,
		LicenseKeyIsNotValidForDeactivation,
		LicenseKeyIsNotValidForSelectedOEM,
		LicenseKeyIsNotValidForSelectedTypeOfActivation,
		LicenseKeyMustBeEntered,
		LicenseKeyVersionIsNotValid,
		LicenseKeyWasAlreadyDeactivated,
		LicenseKeyWasAlreadyUpgraded,
		LicenseKeyWasIssuedWithDongle,
		LicenseKeyWasIssuedWithDongleAndCanNotBeDeactivated,
		LicenseKeyWasNotActivatedYetAndCanNotBeDeactivated,
		LicensePackCannotBeDeactivated,
		NameMustBeEntered,
		ReasonForAnotherActivationRequired,
		RegistrationNumberIsNotValid,
		RegistrationNumberMustBeEntered
	}
}
